#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyIngresso.DAO.Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Easy_Ingresso")]
	public partial class ModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAcessoEasyIngresso(AcessoEasyIngresso instance);
    partial void UpdateAcessoEasyIngresso(AcessoEasyIngresso instance);
    partial void DeleteAcessoEasyIngresso(AcessoEasyIngresso instance);
    partial void InsertCadastro(Cadastro instance);
    partial void UpdateCadastro(Cadastro instance);
    partial void DeleteCadastro(Cadastro instance);
    partial void InsertSituacao(Situacao instance);
    partial void UpdateSituacao(Situacao instance);
    partial void DeleteSituacao(Situacao instance);
    #endregion
		
		public ModelDataContext() : 
				base(global::EasyIngresso.DAO.Properties.Settings.Default.DB_Easy_IngressoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AcessoEasyIngresso> AcessoEasyIngressos
		{
			get
			{
				return this.GetTable<AcessoEasyIngresso>();
			}
		}
		
		public System.Data.Linq.Table<Cadastro> Cadastros
		{
			get
			{
				return this.GetTable<Cadastro>();
			}
		}
		
		public System.Data.Linq.Table<Situacao> Situacaos
		{
			get
			{
				return this.GetTable<Situacao>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AcessoEasyIngresso")]
	public partial class AcessoEasyIngresso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codPessoa;
		
		private string _nmPessoa;
		
		private string _nmLogon;
		
		private string _nmPassword;
		
		private System.Nullable<System.DateTime> _nmDataCriacao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodPessoaChanging(int value);
    partial void OncodPessoaChanged();
    partial void OnnmPessoaChanging(string value);
    partial void OnnmPessoaChanged();
    partial void OnnmLogonChanging(string value);
    partial void OnnmLogonChanged();
    partial void OnnmPasswordChanging(string value);
    partial void OnnmPasswordChanged();
    partial void OnnmDataCriacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnnmDataCriacaoChanged();
    #endregion
		
		public AcessoEasyIngresso()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPessoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codPessoa
		{
			get
			{
				return this._codPessoa;
			}
			set
			{
				if ((this._codPessoa != value))
				{
					this.OncodPessoaChanging(value);
					this.SendPropertyChanging();
					this._codPessoa = value;
					this.SendPropertyChanged("codPessoa");
					this.OncodPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmPessoa", DbType="VarChar(250)")]
		public string nmPessoa
		{
			get
			{
				return this._nmPessoa;
			}
			set
			{
				if ((this._nmPessoa != value))
				{
					this.OnnmPessoaChanging(value);
					this.SendPropertyChanging();
					this._nmPessoa = value;
					this.SendPropertyChanged("nmPessoa");
					this.OnnmPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmLogon", DbType="VarChar(50)")]
		public string nmLogon
		{
			get
			{
				return this._nmLogon;
			}
			set
			{
				if ((this._nmLogon != value))
				{
					this.OnnmLogonChanging(value);
					this.SendPropertyChanging();
					this._nmLogon = value;
					this.SendPropertyChanged("nmLogon");
					this.OnnmLogonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmPassword", DbType="VarChar(50)")]
		public string nmPassword
		{
			get
			{
				return this._nmPassword;
			}
			set
			{
				if ((this._nmPassword != value))
				{
					this.OnnmPasswordChanging(value);
					this.SendPropertyChanging();
					this._nmPassword = value;
					this.SendPropertyChanged("nmPassword");
					this.OnnmPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmDataCriacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> nmDataCriacao
		{
			get
			{
				return this._nmDataCriacao;
			}
			set
			{
				if ((this._nmDataCriacao != value))
				{
					this.OnnmDataCriacaoChanging(value);
					this.SendPropertyChanging();
					this._nmDataCriacao = value;
					this.SendPropertyChanged("nmDataCriacao");
					this.OnnmDataCriacaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cadastro")]
	public partial class Cadastro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCadastro;
		
		private string _nome;
		
		private string _Endereco;
		
		private string _CPF;
		
		private string _Complemento;
		
		private string _Numero;
		
		private string _Bairro;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _CEP;
		
		private string _Telefone;
		
		private string _Celular;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DataNascimento;
		
		private System.Nullable<System.DateTime> _DataCriacao;
		
		private System.Nullable<int> _codSituacao;
		
		private System.Nullable<System.DateTime> _DataSituacao;
		
		private System.Nullable<System.DateTime> _DataBloqueio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCadastroChanging(int value);
    partial void OnidCadastroChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnComplementoChanging(string value);
    partial void OnComplementoChanged();
    partial void OnNumeroChanging(string value);
    partial void OnNumeroChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDataNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataNascimentoChanged();
    partial void OnDataCriacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCriacaoChanged();
    partial void OncodSituacaoChanging(System.Nullable<int> value);
    partial void OncodSituacaoChanged();
    partial void OnDataSituacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataSituacaoChanged();
    partial void OnDataBloqueioChanging(System.Nullable<System.DateTime> value);
    partial void OnDataBloqueioChanged();
    #endregion
		
		public Cadastro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCadastro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idCadastro
		{
			get
			{
				return this._idCadastro;
			}
			set
			{
				if ((this._idCadastro != value))
				{
					this.OnidCadastroChanging(value);
					this.SendPropertyChanging();
					this._idCadastro = value;
					this.SendPropertyChanged("idCadastro");
					this.OnidCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(250)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="VarChar(70)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(11)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complemento", DbType="VarChar(40)")]
		public string Complemento
		{
			get
			{
				return this._Complemento;
			}
			set
			{
				if ((this._Complemento != value))
				{
					this.OnComplementoChanging(value);
					this.SendPropertyChanging();
					this._Complemento = value;
					this.SendPropertyChanged("Complemento");
					this.OnComplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(10)")]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(10)")]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(40)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(9)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(20)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(20)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(60)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DataNascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCriacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataCriacao
		{
			get
			{
				return this._DataCriacao;
			}
			set
			{
				if ((this._DataCriacao != value))
				{
					this.OnDataCriacaoChanging(value);
					this.SendPropertyChanging();
					this._DataCriacao = value;
					this.SendPropertyChanged("DataCriacao");
					this.OnDataCriacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codSituacao", DbType="Int")]
		public System.Nullable<int> codSituacao
		{
			get
			{
				return this._codSituacao;
			}
			set
			{
				if ((this._codSituacao != value))
				{
					this.OncodSituacaoChanging(value);
					this.SendPropertyChanging();
					this._codSituacao = value;
					this.SendPropertyChanged("codSituacao");
					this.OncodSituacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSituacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataSituacao
		{
			get
			{
				return this._DataSituacao;
			}
			set
			{
				if ((this._DataSituacao != value))
				{
					this.OnDataSituacaoChanging(value);
					this.SendPropertyChanging();
					this._DataSituacao = value;
					this.SendPropertyChanged("DataSituacao");
					this.OnDataSituacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataBloqueio", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataBloqueio
		{
			get
			{
				return this._DataBloqueio;
			}
			set
			{
				if ((this._DataBloqueio != value))
				{
					this.OnDataBloqueioChanging(value);
					this.SendPropertyChanging();
					this._DataBloqueio = value;
					this.SendPropertyChanged("DataBloqueio");
					this.OnDataBloqueioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Situacao")]
	public partial class Situacao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Descricao;
		
		private System.Nullable<byte> _Situacao1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnSituacao1Changing(System.Nullable<byte> value);
    partial void OnSituacao1Changed();
    #endregion
		
		public Situacao()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(30)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Situacao", Storage="_Situacao1", DbType="TinyInt")]
		public System.Nullable<byte> Situacao1
		{
			get
			{
				return this._Situacao1;
			}
			set
			{
				if ((this._Situacao1 != value))
				{
					this.OnSituacao1Changing(value);
					this.SendPropertyChanging();
					this._Situacao1 = value;
					this.SendPropertyChanged("Situacao1");
					this.OnSituacao1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
